# Generated by Django 3.1.2 on 2020-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
